# Generated by Django 3.2.13 on 2022-12-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('create_time', models.IntegerField(default=1669977522)),
                ('update_time', models.IntegerField(default=1669977522, verbose_name='最后更新时间')),
                ('role_name', models.CharField(max_length=32, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='角色名称')),
                ('data_status', models.IntegerField(default=1, verbose_name='数据状态')),
            ],
            options={
                'db_table': 'sh_user_role',
            },
        ),
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('create_time', models.IntegerField(default=1669977522)),
                ('update_time', models.IntegerField(default=1669977522, verbose_name='最后更新时间')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户账号')),
                ('user_password', models.CharField(max_length=128, verbose_name='用户密码')),
                ('email', models.CharField(blank=True, max_length=32, verbose_name='邮箱信息')),
                ('telephone', models.CharField(blank=True, max_length=16, verbose_name='手机号码')),
                ('nickname', models.CharField(blank=True, max_length=32, verbose_name='用户昵称')),
                ('avatar_url', models.CharField(blank=True, max_length=128, verbose_name='头像地址')),
                ('data_status', models.IntegerField(default=1, verbose_name='数据状态')),
                ('sh_user_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_manage.userrolemodel', verbose_name='用户角色id')),
            ],
            options={
                'db_table': 'sh_user_info',
            },
        ),
    ]
