# Generated by Django 3.2.13 on 2022-12-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCodeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('create_time', models.IntegerField(default=1669977522)),
                ('update_time', models.IntegerField(default=1669977522, verbose_name='最后更新时间')),
                ('auth_code', models.TextField(blank=True, verbose_name='授权码信息')),
                ('auth_company', models.CharField(blank=True, max_length=64, verbose_name='授权方公司')),
                ('auth_project', models.CharField(blank=True, max_length=64, verbose_name='授权项目名称')),
                ('resource_num', models.IntegerField(blank=True, verbose_name='授权接入设备数量')),
                ('start_time', models.CharField(blank=True, max_length=16, verbose_name='激活时间')),
                ('end_time', models.CharField(blank=True, max_length=16, verbose_name='结束时间')),
                ('data_status', models.IntegerField(default=1, verbose_name='数据状态')),
            ],
            options={
                'db_table': 'sh_authorization_code',
            },
        ),
    ]
